[[source]]
fqdn = "localhost"

# [filesink]
# retain_hours = 24

[app]
# logstash = "D30:8888"
summary = true # prints a summary of events to stdout after running
samples = true # prints one of each type event to samples.xe.json after running

[defaults]
sessions = ["system_health"]
rows = 1 
look_back = "24h"
timestamp_field_name = "@timestamp"
payload_field_name = "mssql" # all the XE events are under this field
agentjobs = "all" # process SQL Server agent job history
excludedEvents = [
    "connectivity_ring_buffer_recorded",
    "memory_broker_ring_buffer_recorded",
    "scheduler_monitor_system_health_ring_buffer_recorded",
    "security_error_ring_buffer_recorded"
    ]

[applog]
# logstash = "D30:8888"
timestamp_field_name = "@timestamp"
samples = true # prints the JSON application logging messaegs to samples.applog.json





